# use Ganache's forked mainnet mode as the default network
networks:
  default: development

# require OpenZepplin Contracts
dependencies:
  - lbertenasco/openzeppelin-contracts@3.1.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelin=lbertenasco/openzeppelin-contracts@3.1.0"

